MVCContribGrid/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCContribGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Salary { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
    }
}

MVCContribGrid/Models/SampleDBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCContribGrid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCContribModel : DbContext
    {
        public MVCContribModel()
            : base("name=MVCContribModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
    }
}

MVCContribGrid/Models/SampleDBModel.Designer.cs
// T4 code generation is enabled for model 'C:\development\MVCContribGrid\MVCContribGrid\Models\SampleDBModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVCContribGrid/Models/SampleDBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVCContribGrid/Controllers/MVCContribController.cs
using MvcContrib.Pagination;
using MvcContrib.UI.Grid;
using MVCContribGrid.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCContribGrid.Controllers
{
    public class MVCContribController : Controller
    {
        MVCContribModel db = new MVCContribModel();
        //
        // GET: /MVCContrib/
        public ActionResult Index(GridSortOptions sort, int? page)
        {
            IPagination<Employee> emp = null;
          
            if (sort.Column == null) sort.Column = "Name";
            if (sort.Direction.ToString().ToLower() == "descending")
                emp = db.Employees.AsEnumerable().OrderByDescending(i => i.GetType().GetProperty(sort.Column).GetValue(i, null)).AsPagination(page ?? 1, 2);
            else
                emp = db.Employees.AsEnumerable().OrderBy(i => i.GetType().GetProperty(sort.Column).GetValue(i, null)).AsPagination(page ?? 1, 2);

            ViewData["sort"] = sort;
            return View(emp);
        }

        //public ActionResult Index(int? page)
        //{
        //    return View(db.Employees.ToList());
        //} 




        //public ActionResult Details(int id = 0)  
        // {  
        //     Employee employee = db.Employees.Find(id);  
        //     if (employee == null)  
        //     {  
        //         return HttpNotFound();  
        //     }  
        //     return View(employee);  
        // }  

        // //  
        // // GET: /Employee/Create  

        // public ActionResult Create()  
        // {  
        //     return View();  
        // }  

        // //  
        // // POST: /Employee/Create  

        // [HttpPost]  
        // public ActionResult Create(Employee employee)  
        // {  
        //     if (ModelState.IsValid)  
        //     {  
        //         db.Employees.Add(employee);  
        //         db.SaveChanges();  
        //         return RedirectToAction("Index");  
        //     }  

        //     return View(employee);  
        // }  

        // //  
        // // GET: /Employee/Edit/5  

        // public ActionResult Edit(int id = 0)  
        // {  
        //     Employee employee = db.Employees.Find(id);  
        //     if (employee == null)  
        //     {  
        //         return HttpNotFound();  
        //     }  
        //     return View(employee);  
        // }  

        // //  
        // // POST: /Employee/Edit/5  

        // [HttpPost]  
        // public ActionResult Edit(Employee employee)  
        // {  
        //     if (ModelState.IsValid)  
        //     {  
        //         db.Entry(employee).State = EntityState.Modified;  
        //         db.SaveChanges();  
        //         return RedirectToAction("Index");  
        //     }  
        //     return View(employee);  
        // }  

        // //  
        // // GET: /Employee/Delete/5  

        // public ActionResult Delete(int id = 0)  
        // {  
        //     Employee employee = db.Employees.Find(id);  
        //     if (employee == null)  
        //     {  
        //         return HttpNotFound();  
        //     }  
        //     return View(employee);  
        // }  

        // //  
        // // POST: /Employee/Delete/5  

        // [HttpPost, ActionName("Delete")]  
        // public ActionResult DeleteConfirmed(int id)  
        // {  
        //     Employee employee = db.Employees.Find(id);  
        //     db.Employees.Remove(employee);  
        //     db.SaveChanges();  
        //     return RedirectToAction("Index");  
        // }  

        // protected override void Dispose(bool disposing)  
        // {  
        //     db.Dispose();  
        //     base.Dispose(disposing);  
        // }  
    }

}

MVCContribGrid/Views/MVCContrib/Create.cshtml
@model MVCContribGrid.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>MVCContrib Grid - Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation)
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary)
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip)
                @Html.ValidationMessageFor(model => model.Zip)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVCContribGrid/Views/MVCContrib/Delete.cshtml
@model MVCContribGrid.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>MVCContrib Grid - Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCContribGrid/Views/MVCContrib/Details.cshtml
@model MVCContribGrid.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>MVCContrib Grid - Details</h2>

<div>
    <h4>Employee</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCContribGrid/Views/MVCContrib/Edit.cshtml
@model MVCContribGrid.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>MVCContrib Grid - Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Designation)
                @Html.ValidationMessageFor(model => model.Designation)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary)
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip)
                @Html.ValidationMessageFor(model => model.Zip)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVCContribGrid/Views/MVCContrib/Index.cshtml
@model IPagination<MVCContribGrid.Models.Employee>
@using MvcContrib.UI.Grid;
@using MvcContrib.Pagination;
@using MvcContrib.UI.Pager;
@using MvcContrib.Sorting;



<style>

    .grid {
        font-family: Arial,Helvetica,sans-serif;
        font-size: 14px;
        font-weight: normal;
        width: 650px;
        display: table;
        border-collapse: collapse;
        border: solid 1px #C5C5C5;
        background-color: white;
    }

        .grid td, th {
            border: 1px solid #C5C5C5;
            padding: 3px 7px 2px;
        }

        .grid thead, .header a {
            background-color: #0094ff;
            color: #ffffff;
            text-align: left;
            text-decoration: none;
        }

    .grid-footer {
    }

    .grid-row-style {
        padding: 3px 7px 2px;
    }

    .grid-alternating-row {
        background-color: azure;
        padding: 3px 7px 2px;
    }

    .col1Width {
        width: 55px;
    }

    .col2Width {
        width: 220px;
    }
</style>

<h2>MVCContrib Grid - Index</h2>
<div id="pager">
    @Html.Pager((IPagination)Model) 
</div>
<p>
    @Html.ActionLink("Create New", "Create")
    @Html.Grid(Model).AutoGenerateColumns().Sort((GridSortOptions)ViewData["sort"])
   
</p>
@*<p>
    @Html.Grid(Model).Columns(col =>
{
    col.For(p => p.Name);
    col.For(p => p.Designation);
    col.For(p => p.Gender);
    col.For(p => p.Salary);
    col.For(p => p.City);
    col.For(p => p.State);
    col.For(p => p.Zip);
    col.For(p => Html.ActionLink("Edit", "Edit", "MVCContrib", new { id = p.id }, new { }));
    col.For(p => Html.ActionLink("Details", "Details", "MVCContrib", new { id = p.id }, new { }));
    col.For(p => Html.ActionLink("Delete", "Delete", "MVCContrib", new { id = p.id }, new { }));
}).Attributes(id => "example")
</p>*@

MVCContribGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @*<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>*@
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>www.techstrikers.com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>